name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and coverage
      run: |
        pytest --cov=./src
        coverage html
      shell: bash

    - name: Save coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov

    - name: Generate coverage comment
      uses: rabelenda/python-coverage-comment@v1
      with:
        artifact: coverage-report
        artifact-type: path
